version: '3'

services:
  etl:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/app/data
    command: python src/main.py

  dash-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/app/data
    ports:
      - "8050:8050"
    depends_on:
      - etl
    command: python src/app.py
    environment:
      - FLASK_RUN_PORT=8050
